package identity

// Frequent given names and surnames across the networks Beeper bridges.
// A full name whose first and last words both appear here is treated as
// common: two distinct humans could plausibly share it, so a cross-account
// merge on that name alone waits for user approval. Coverage errs toward
// listing more names, since a false "common" only costs one approval while
// a false "rare" silently merges strangers.

var commonFirstNames = toSet([]string{
	"james", "john", "robert", "michael", "william", "david", "richard",
	"joseph", "thomas", "charles", "christopher", "chris", "daniel", "matthew",
	"matt", "anthony", "mark", "donald", "steven", "steve", "paul", "andrew",
	"andy", "joshua", "josh", "kenneth", "ken", "kevin", "brian", "george",
	"timothy", "tim", "ronald", "ron", "edward", "ed", "jason", "jeffrey",
	"jeff", "ryan", "jacob", "jake", "gary", "nicholas", "nick", "eric",
	"jonathan", "jon", "stephen", "larry", "justin", "scott", "brandon",
	"benjamin", "ben", "samuel", "sam", "gregory", "greg", "frank",
	"alexander", "alex", "raymond", "ray", "patrick", "pat", "jack", "dennis",
	"jerry", "tyler", "aaron", "jose", "adam", "nathan", "nate", "henry",
	"douglas", "doug", "zachary", "zach", "peter", "pete", "kyle", "ethan",
	"walter", "noah", "jeremy", "christian", "keith", "roger", "terry",
	"austin", "sean", "gerald", "carl", "harold", "dylan", "jordan", "jesse",
	"bryan", "billy", "bruce", "gabriel", "gabe", "joe", "logan", "alan",
	"juan", "albert", "willie", "elijah", "wayne", "randy", "mason",
	"vincent", "liam", "oliver", "lucas", "luke", "owen", "leo", "max",
	"tom", "tony", "mike", "dave", "dan", "rob", "bob", "bill", "will",
	"mary", "patricia", "jennifer", "jen", "linda", "elizabeth", "liz",
	"barbara", "susan", "sue", "jessica", "jess", "sarah", "sara", "karen",
	"lisa", "nancy", "betty", "sandra", "margaret", "ashley", "kimberly",
	"kim", "emily", "donna", "michelle", "carol", "amanda", "melissa",
	"deborah", "deb", "stephanie", "steph", "rebecca", "becca", "sharon",
	"laura", "cynthia", "amy", "kathleen", "kathy", "angela", "shirley",
	"brenda", "emma", "anna", "pamela", "pam", "nicole", "samantha",
	"katherine", "kate", "katie", "christine", "helen", "debra", "rachel",
	"carolyn", "janet", "maria", "catherine", "cat", "heather", "diane",
	"olivia", "julie", "victoria", "vicky", "joyce", "lauren", "kelly",
	"christina", "ruth", "joan", "virginia", "judith", "judy", "evelyn",
	"hannah", "andrea", "megan", "meg", "alice", "cheryl", "jacqueline",
	"sophia", "sophie", "frances", "jean", "gloria", "kathryn", "ann",
	"anne", "teresa", "doris", "julia", "grace", "amber", "denise",
	"danielle", "marilyn", "beverly", "charlotte", "natalie", "nat",
	"theresa", "diana", "sofia", "mia", "isabella", "bella", "ava", "zoe",
	"chloe", "dana", "ella", "lily", "lucy", "nina", "eva", "clara",
	"mohammed", "mohammad", "muhammad", "ahmed", "ahmad", "ali", "omar",
	"yusuf", "ibrahim", "hassan", "hussein", "mustafa", "khalid", "tariq",
	"fatima", "aisha", "layla", "leila", "zainab", "mariam", "maryam",
	"wei", "ming", "hui", "jing", "li", "na", "min", "jun", "hao", "lei",
	"yan", "fang", "ying", "xin", "yu", "chen", "akira", "yuki", "kenji",
	"hiroshi", "takeshi", "haruto", "yuto", "sakura", "yui", "hana",
	"carlos", "jorge", "luis", "miguel", "pedro", "pablo", "diego",
	"alejandro", "santiago", "sebastian", "mateo", "javier", "fernando",
	"ricardo", "eduardo", "roberto", "antonio", "manuel", "francisco",
	"camila", "valentina", "lucia", "martina", "elena", "carmen", "rosa",
	"isabel", "ana", "priya", "raj", "amit", "rohan", "ananya", "arjun",
	"vikram", "sanjay", "anil", "ravi", "rahul", "deepak", "vijay", "ajay",
	"suresh", "ramesh", "neha", "pooja", "anjali", "kavya", "aditi",
	"minh", "anh", "linh", "huong", "duc", "tuan", "hung", "nam",
	"ivan", "dmitri", "sergei", "andrei", "alexei", "olga", "natasha",
	"svetlana", "irina", "elena", "hans", "klaus", "stefan", "jan",
	"lars", "erik", "sven", "anders", "johan", "pierre", "jacques",
	"louis", "marie", "claire", "camille", "marco", "luca", "matteo",
	"giovanni", "giulia", "francesca", "joao", "tiago", "rafael",
	"gabriela", "beatriz", "kwame", "kofi", "amara", "chidi", "ngozi",
	"emeka", "tunde", "sipho", "thabo",
})

var commonSurnames = toSet([]string{
	"smith", "johnson", "williams", "brown", "jones", "garcia", "miller",
	"davis", "rodriguez", "martinez", "hernandez", "lopez", "gonzalez",
	"wilson", "anderson", "thomas", "taylor", "moore", "jackson", "martin",
	"lee", "perez", "thompson", "white", "harris", "sanchez", "clark",
	"ramirez", "lewis", "robinson", "walker", "young", "allen", "king",
	"wright", "scott", "torres", "nguyen", "hill", "flores", "green",
	"adams", "nelson", "baker", "hall", "rivera", "campbell", "mitchell",
	"carter", "roberts", "gomez", "phillips", "evans", "turner", "diaz",
	"parker", "cruz", "edwards", "collins", "reyes", "stewart", "morris",
	"morales", "murphy", "cook", "rogers", "gutierrez", "ortiz", "morgan",
	"cooper", "peterson", "bailey", "reed", "kelly", "howard", "ramos",
	"cox", "richardson", "watson", "brooks", "chavez", "wood", "james",
	"bennett", "gray", "mendoza", "ruiz", "hughes", "price", "alvarez",
	"castillo", "sanders", "patel", "myers", "long", "ross", "foster",
	"jimenez", "powell", "jenkins", "perry", "russell", "sullivan", "bell",
	"coleman", "butler", "henderson", "barnes", "fisher", "vasquez",
	"simmons", "romero", "jordan", "patterson", "alexander", "hamilton",
	"graham", "reynolds", "griffin", "wallace", "moreno", "west", "cole",
	"hayes", "bryant", "herrera", "gibson", "ellis", "tran", "medina",
	"aguilar", "stevens", "murray", "ford", "castro", "marshall", "owens",
	"harrison", "fernandez", "mcdonald", "woods", "washington", "kennedy",
	"wells", "vargas", "henry", "chen", "freeman", "webb", "tucker",
	"guzman", "burns", "crawford", "olson", "simpson", "porter", "hunter",
	"gordon", "mendez", "silva", "shaw", "snyder", "mason", "dixon",
	"munoz", "hunt", "hicks", "holmes", "palmer", "wagner", "black",
	"robertson", "boyd", "rose", "stone", "salazar", "fox", "warren",
	"mills", "meyer", "rice", "schmidt", "daniels", "ferguson", "nichols",
	"stephens", "soto", "weaver", "ryan", "gardner", "payne", "grant",
	"dunn", "kelley", "spencer", "hawkins", "arnold", "pierce", "vazquez",
	"hansen", "peters", "santos", "hart", "bradley", "knight", "elliott",
	"cunningham", "duncan", "armstrong", "hudson", "carroll", "lane",
	"riley", "andrews", "alvarado", "ray", "delgado", "berry", "perkins",
	"hoffman", "johnston", "matthews", "pena", "richards", "contreras",
	"willis", "carpenter", "lawrence", "sandoval", "guerrero", "george",
	"chapman", "rios", "estrada", "ortega", "watkins", "greene", "nunez",
	"wheeler", "valdez", "harper", "burke", "larson", "santiago",
	"maldonado", "morrison", "franklin", "carlson", "austin", "dominguez",
	"carr", "lawson", "jacobs", "obrien", "lynch", "singh", "vega",
	"bishop", "montgomery", "oliver", "jensen", "harvey", "williamson",
	"gilbert", "dean", "sims", "espinoza", "howell", "li", "wang", "zhang",
	"liu", "yang", "huang", "zhao", "wu", "zhou", "xu", "sun", "ma", "zhu",
	"hu", "guo", "he", "gao", "lin", "luo", "zheng", "liang", "xie",
	"song", "tang", "han", "feng", "deng", "cao", "peng", "zeng", "xiao",
	"tian", "dong", "pan", "yuan", "cai", "jiang", "yu", "du", "ye",
	"cheng", "wei", "lu", "ding", "shen", "fan", "jin", "shi", "yao",
	"tan", "kim", "park", "choi", "jung", "kang", "cho", "yoon", "jang",
	"lim", "han", "oh", "shin", "kwon", "hwang", "ahn", "song", "yoo",
	"hong", "sato", "suzuki", "takahashi", "tanaka", "watanabe", "ito",
	"yamamoto", "nakamura", "kobayashi", "kato", "yoshida", "yamada",
	"sasaki", "yamaguchi", "saito", "matsumoto", "inoue", "kimura",
	"hayashi", "shimizu", "kumar", "sharma", "khan", "ahmed", "ali",
	"hassan", "hussain", "shah", "gupta", "mehta", "verma", "rao",
	"reddy", "nair", "iyer", "das", "bose", "chowdhury", "rahman",
	"islam", "begum", "malik", "sheikh", "syed", "mirza", "qureshi",
	"le", "pham", "hoang", "phan", "vu", "vo", "dang", "bui", "do",
	"ho", "ngo", "duong", "ly", "mueller", "muller", "schneider",
	"fischer", "weber", "becker", "schulz", "hoffmann", "koch", "richter",
	"klein", "wolf", "neumann", "schwarz", "braun", "kruger", "hofmann",
	"lange", "schmitt", "werner", "krause", "meier", "lehmann", "keller",
	"jansen", "de jong", "de vries", "van den berg", "bakker", "visser",
	"andersson", "johansson", "karlsson", "nilsson", "eriksson", "larsson",
	"olsson", "persson", "svensson", "hansen", "johansen", "olsen",
	"pedersen", "andersen", "nielsen", "jorgensen", "petersen",
	"martin", "bernard", "dubois", "thomas", "robert", "richard", "petit",
	"durand", "leroy", "moreau", "simon", "laurent", "lefebvre", "michel",
	"garcia", "rossi", "russo", "ferrari", "esposito", "bianchi", "romano",
	"colombo", "ricci", "marino", "greco", "bruno", "gallo", "conti",
	"costa", "giordano", "mancini", "rizzo", "lombardi", "moretti",
	"pereira", "oliveira", "souza", "lima", "carvalho", "ribeiro",
	"almeida", "alves", "monteiro", "mendes", "barbosa", "cardoso",
	"teixeira", "correia", "ivanov", "smirnov", "kuznetsov", "popov",
	"petrov", "sokolov", "volkov", "fedorov", "kozlov", "novikov",
	"morozov", "kowalski", "nowak", "wisniewski", "wojcik", "kaminski",
	"lewandowski", "zielinski", "szymanski", "dabrowski", "horvath",
	"kovacs", "nagy", "toth", "szabo", "papadopoulos", "yilmaz", "kaya",
	"demir", "celik", "sahin", "ozturk", "aydin", "ozdemir", "arslan",
	"dogan", "abebe", "tesfaye", "mohammed", "okafor", "okonkwo", "eze",
	"adeyemi", "adebayo", "okoro", "mensah", "boateng", "osei", "diallo",
	"traore", "toure", "ndiaye", "diop", "sow", "ba", "fall", "gueye",
	"moyo", "ncube", "dube", "khumalo", "ngcobo", "dlamini", "mokoena",
	"botha", "van der merwe", "pretorius", "venter", "cohen", "levi",
	"levy", "mizrahi", "peretz", "biton", "friedman", "goldberg",
	"rosenberg", "katz", "shapiro",
})

func toSet(names []string) map[string]bool {
	set := make(map[string]bool, len(names))
	for _, n := range names {
		set[n] = true
	}
	return set
}
